### ISSUE TITLE
Better explanation of what's shown in Routes

### ISSUE THREAD

**Issue by ai-slave** [LlamaSwap/interface#14]
I'd ask team to come up with a description for a swap so I can impove user expectations a little bit 

<img width="424" alt="image" src="https://user-images.githubusercontent.com/6696080/212202491-7889f9aa-118b-4055-b1a6-a1a22e3d42be.png">

_Originally posted by @ai-slave in https://github.com/LlamaSwap/interface/issues/12#issuecomment-1381101896_

**Comment by 0xngmi** [comment]
good idea

**Comment by ai-slave** [comment]
Added in #12
