### ISSUE TITLE
Pre-filled mode breaks swap button

### ISSUE THREAD

**Issue by ai-slave** [LlamaSwap/interface#24]
If you open swap page with input/output params and wallet connects automatically – swap btns doesn't work and throw overflow. 

https://swap.defillama.com/?from=0x0000000000000000000000000000000000000000&to=0x2260fac5e5542a773aa44fbcfedf7c193bc2c599

<img width="328" alt="image" src="https://user-images.githubusercontent.com/6696080/212467324-52bf6a9a-7b2a-4b16-afeb-d137dc55963e.png">

<img width="340" alt="image" src="https://user-images.githubusercontent.com/6696080/212467357-0ed286c9-5246-4b49-ba48-ab8491fd7da7.png">

Maybe my Frame is just buggy, but pls test that it isn't happening for you.

**Comment by 0xngmi** [comment]
having trouble reproducing this with my metamask
